blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pagina.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pagina/urls.py
from django.urls import path
from . import views
from django.urls import reverse

app_name = "pagina"
urlpatterns = [
    path('', views.index, name="index"),
    path('item/<int:item_id>', views.itemView, name="vista"),
    path('carrito/<int:item_id>', views.carrito, name="carrito"),
    path('carritoEliminar/<int:item_id>', views.carritoEliminar, name="carritoEliminar"),
    path('item/crear', views.itemCreate, name="nuevo"),
    path('item/editar/<int:item_id>', views.itemUpdate, name="editar"),
    path('item/eliminar/<int:item_id>', views.itemDelete, name="eliminar"),
    path('categoria/<int:categoria_id>', views.filtroCategoria, name="categoria"),
    path('vistaCarrito', views.botonCarrito, name="vistaCarrito"),
    path('acercade', views.acercade, name="acercade"),
    path('contacto', views.contacto, name="contacto"),
    path('registro', views.registro, name="registro"),
]

pagina/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse

# Create your models here.
class Categoria(models.Model):
    descripcion = models.CharField(max_length=50)

    def __str__(self):
        return self.descripcion

class Item(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, related_name="clasificacion")
    titulo = models.CharField(max_length=100, null=False)
    precio = models.IntegerField(default=0)
    contenido = models.CharField(max_length=1000, null=False)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    ultima_edicion = models.DateTimeField(auto_now=True)
    imagen = models.ImageField(upload_to='images/', null=True)
    editor = models.ForeignKey(User, on_delete=models.CASCADE, related_name="publicador")

    def __str__(self):
        return self.titulo
    
    def get_absolute_url(self):
        return reverse("detail", kwargs={
            "item_id": self.Item_id
        })
    
class Carrito(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name="usuario")
    compras = models.ManyToManyField(Item)

    def __str__(self):
        return f"{self.usuario} - {self.compras}"

class Contacto(models.Model):
    nombre = models.CharField(max_length=100)
    correo = models.EmailField()
    consulta = models.TextField()
    avisos = models.BooleanField('deseo recibir avisos')

    def __str__(self):
        return self.correo
    

pagina/forms.py
from django import forms
from django.forms import widgets
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Item, Contacto

class NuevoItem(forms.ModelForm):
    
    class Meta:
        model = Item
        fields = ['titulo', 'categoria', 'precio', 'contenido', 'imagen']

        widgets = {
            "fecha_creacion": forms.SelectDateWidget()
        }

class CustomUserCreationForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

class ContactoForm(forms.ModelForm):

    class Meta:
        model = Contacto
        fields = '__all__'

pagina/views.py
from django.contrib.auth.models import User
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from .forms import NuevoItem, CustomUserCreationForm, ContactoForm
from .models import Item, Categoria, Carrito
from django.utils import timezone
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import Q


# Create your views here.
def index(request):
    busq = request.GET.get("buscar")
    items = Item.objects.all()
    if busq:
        items = items.filter(
            Q(titulo__icontains = busq) |
            Q(contenido__icontains = busq)
        ).distinct()
    lista_categorias = reversed(Categoria.objects.all())
    if "carrito" not in request.session:
        request.session["carrito"] = []
    return render(request, 'pagina/index.html', {
        "lista_items": items,
        "lista_categorias": lista_categorias,
        "lista_carrito": request.session["carrito"],
    })

def itemView(request, item_id):
    item = get_object_or_404(Item, id=item_id)
    return render(request, 'pagina/item_vista.html', {
        "item": item,
        "lista_categorias": Categoria.objects.all(),
        "lista_carrito": request.session["carrito"],
    })

@permission_required('pagina.add_item')
def itemCreate(request):
    if request.method == "POST":
        user = User.objects.get(username=request.user)
        form = NuevoItem(request.POST, request.FILES, instance=Item(imagen=request.FILES['imagen'], editor=user))
        if form.is_valid():
            form.save()
            return redirect('pagina:index', {
                "lista_categorias": Categoria.objects.all(),
            })
    else:
        form = NuevoItem(initial={'fecha_creacion':timezone.now()})
        return render(request, 'pagina/item_crear.html', {
            "form": form,
            "lista_categorias": Categoria.objects.all(),
        })

@permission_required('pagina.change_item')
def itemUpdate(request, item_id):
    item = get_object_or_404(Item, id=item_id)
    if request.method == "POST":  
        user = User.objects.get(username=request.user)   
        item.editor = user
        form = NuevoItem(data=request.POST, files=request.FILES, instance=item)
        if form.is_valid():
            form.save()
            return redirect("pagina:index")
    else:
        form = NuevoItem(instance = item)
        return render(request, 'pagina/item_edicion.html', {
            "item": item,
            "form": form
        })

@permission_required('pagina.delete_item')
def itemDelete(request, item_id):
    item = get_object_or_404(Item, id=item_id)
    item.delete()
    return redirect("pagina:index")


def filtroCategoria(request, categoria_id):
    filtro = get_object_or_404(Categoria, id=categoria_id)
    items = Item.objects.all()
    items = items.filter(categoria=filtro)
    return render(request, 'pagina/index.html', {
        "lista_items": items,
        "lista_categorias": Categoria.objects.all(),
        "categoria_filtro": filtro
    })

@login_required
def carrito(request, item_id):
    un_item = get_object_or_404(Item, id=item_id)
    for i in request.session["carrito"]:
        if i["id"] == un_item.id:
            #existe el item
            return HttpResponseRedirect(reverse("pagina:vista", args=(un_item.id,)))            
    #request.session["carrito"] += [(un_item.titulo, un_item.precio)]
    request.session["carrito"] += [{
        "titulo": un_item.titulo,
        "precio": un_item.precio,
        "id": un_item.id
    }]
    return HttpResponseRedirect(reverse("pagina:vista", args=(un_item.id,)))

@login_required
def carritoEliminar(request, item_id):
    un_item = get_object_or_404(Item, id=item_id) #objeto entero

    for i in request.session["carrito"]:
        if i == un_item:
            carritod = request.session["carrito"]
            carritod.remove(i)
            request.session["carrito"] = carritod
        return render(request, 'pagina/carrito.html')
    
@login_required
def botonCarrito(request):
    carrito = request.session["carrito"]
    return render(request, 'pagina/carrito.html', {
        "lista_carrito": carrito,
        "lista_categorias": Categoria.objects.all(),
    })


def acercade(request):
    return render(request, 'pagina/acerca_de.html', {
        "lista_categorias": Categoria.objects.all(),
    })

def contacto(request):
    form = ContactoForm()

    if request.method == 'POST':
        formulario = ContactoForm(data=request.POST)
        if formulario.is_valid():
            formulario.save

    return render(request, 'pagina/contacto.html', {
        "lista_categorias": Categoria.objects.all(),
        "form": form
    })

def registro(request):
    data = {
        "form": CustomUserCreationForm()
    }
    if request.method == 'POST':
        formulario = CustomUserCreationForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username=formulario.cleaned_data["username"], password=formulario.cleaned_data["password1"])
            login(request, user)
            return redirect('pagina:index')
        data["form"] = formulario
    return render(request, 'registration/registro.html', data)

pagina/templates/pagina/Item_crear.html
{% extends 'pagina/layout.html' %}
{% block content %}
{% load crispy_forms_tags %}
    <br>
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    <h2>Publica un nuevo item</h2>
                    <hr>
                    <form class="" enctype="multipart/form-data" action="{% url 'pagina:nuevo' %}" method="post">
                        {% csrf_token %}
                        
                        {{ form | crispy }}
                        <br>
                        <hr>
                        <div class="d-flex justify-content-end">
                            <input type="submit" value="Publicar" class="btn btn-primary">
                        </div>
                        <div class="justify-content-end">
                            <a type="button" href="{% url 'pagina:index' %}" >Volver al inicio</a>
                        </div>
                        
                    </form>
                </div>
            </div>
        </div>
    </div>  
{% endblock %}

pagina/templates/pagina/acerca_de.html
{% extends 'pagina/layout.html' %}
{% block content %}
{% load static %}
    <div class="container-fluid">
        <div class="card w-75 mx-auto">
            <div class="card mb-3">
                <h4 class="card-title text-center">Compra y Vende a la velocidad de un click</h4>
                <img src="{% static 'images/jaguarete.jpg' %}" alt="jaguarete" class="card-img-top" style="max-width:60%; max-height:50%;">
                <div class="card-body">
                    
                    <p class="card-text">Creada en 2016, Jaguarete KAA es una compañia de compra y venta de articulos online lider en países como Argentina, Uruguay, Chile y Brasil.</p>
                    <p class="card-text">Fundada por José Giraudo, cuenta con un grupo profesional muy grande de empleados, y aprovechando el auge de internet, buscando posicionarse como una de las empresas líderes del mercado</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

pagina/templates/pagina/busqueda.html
{% extends 'pagina/layout.html' %}
{% block content %}
    <h1>Desde Busqueda</h1>
    {% if categoria_filtro %}
        <div>{{ categoria_filtro }}</div>
    {% else %}
        <div>Todas las categorías</div>
    {% endif %}
    
    <ul>
        {% for un_item in lista_items %}
            <div class="row">
                <div class="col-12 col-md-6 offset-md-3">
                    <div class="card">
                        <div class="card-body">
                            <a href="{% url 'pagina:vista' un_item.id %}">Ver #{{un_item.id}}</a>
                            {% if perms.pagina.change_item %}
                                <a href="{% url 'pagina:editar' un_item.id %}">Modificar Item</a>
                            {% endif %}
                            {% if perms.pagina.delete_item %}
                                <a href="{% url 'pagina:eliminar' un_item.id %}">Eliminar Item</a>
                            {% endif %}
                            {{ un_item.titulo }}
                            
                            {% empty %}
                                <li>No hay Items en esta categoría</li>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </ul>
    {% if perms.pagina.add_item %}
        <a href="{% url 'pagina:nuevo' %}">Publicar un nuevo Item</a>
        <br>
    {% endif %}



{% endblock %}

pagina/templates/pagina/carrito.html
{% extends 'pagina/layout.html' %}
{% block content %}
    <div class="container-fluid">
        <div class="card w-50 text-center mx-auto">
            <h5 class="card-header">Carrito de compras</h5>
            <div class="card-body">
                {% if lista_carrito %}
                <ul class="list-group list-group-flush">
                    {% for item in lista_carrito %}
                        <div>
                            <p>{{item.titulo}} ----------- $ {{item.precio}}</p>

                        </div>

                        <div class="row">
                            <div class="col-md-6 col-12">
                                <a role="button" class="btn btn-outline-danger" href="{% url 'pagina:carritoEliminar' item.id %}">Eliminar del carrito</a>
                            </div>
                            <div class="col-md-6 col-12">
                                <a role="button" class="btn btn-outline-success" href="#">Comprar Item</a>
                            </div>
                        </div>
                        <hr>
                    {% endfor %}
                {% else %}
                    Agrega items a tu carrito!
                {% endif %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

pagina/templates/pagina/contacto.html
{% extends 'pagina/layout.html' %}
{% block content %}
{% load crispy_forms_tags %}
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    <div class="card-title">
                        <h3>Comunicate con la empresa</h3>
                        <br>
                        <h5>Telefono de contacto: XXXXXXXXXX</h5>
                        <hr>
                        <h5>O deja tu consulta y recibe una respuesta vía e-mail: </h5>
                        <p>(puede tardar varios días)</p>
                    </div>
                    <form action="" class="" method="post">
                        {% csrf_token %}

                        {{ form | crispy }}

                        <br>

                        <button type="submit" class="btn btn-primary">Enviar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

pagina/templates/pagina/index.html
{% extends 'pagina/layout.html' %}
{% block content %}
    <div class="container-fluid">

    <div class="text-center"
            style="
                font-weight: 500;
                font-size: 1em;
                color: #000;
                padding: 0.3em;
                margin-top: 0.5em;
            "
    >
        {% if categoria_filtro %}
            <div>{{ categoria_filtro }}</div>
        {% else %}
            Todas las categorías
        {% endif %}
    </div>
    <hr />
        <div class="row">
        {% for un_item in lista_items %}
            {% if forloop.counter <= 3 %}
           
                    <div class="col-md-4">
                        <div class="card">
                            <div class="card-title text-center">
                                <h4 style="padding:0.5em;">{{un_item.titulo}}</h4>
                            </div> 
                            <div class="card-body">
                                <div class="text-center" >
                                    <p><img
                                        src="{{ media_url }}{{ un_item.imagen.url }}"
                                        class="card-img-bottom img-fluid"
                                        alt="{{ un_item.imagen.name }}"
                                        style="min-height:15em;"
                                    /></p>
                                </div>
                                <hr />
                                <div class="row">
                                    <a class="btn btn-success" href="{% url 'pagina:vista' un_item.id %}">Ver {{un_item.titulo}}</a>
                                </div>
                                <br />
                                <div class="row">
                                    {% if perms.pagina.change_item %}
                                    <div class="col-12 col-md-6 col-sm-12">
                                        <a
                                        style="width: 100%; padding: 0.3em;"
                                        class="btn btn-outline-warning" href="{% url 'pagina:editar' un_item.id %}">Modificar Item</a>
                                    </div>
                                    {% endif %}
                                    {% if perms.pagina.delete_item %}
                                        <div class="col-12 col-md-6 col-sm-12">
                                        <a
                                        style="width: 100%; padding: 0.3em; margin-top: 0.1em;"
                                        class="btn btn-outline-danger btn-block" href="{% url 'pagina:eliminar' un_item.id %}">Eliminar Item</a>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
                
        {% endfor %}
        </div>
        <div class="mt-3 mb-3">
            <div class="text-center">
                <h4>Otros productos</h4>
                <hr>
            </div>
            <div class="row">
                {% for un_item in lista_items %}
                   {% if forloop.counter >= 3 and forloop.counter <= 10 %}
                    <div class="d-grip">
                        <a class="btn btn-outline-info" style="text-decoration: none; border: none; color: black;" href="{% url 'pagina:vista' un_item.id %}" >{{un_item.titulo}}: {{un_item.contenido}}</a>
                    </div>
                   {% endif %}
                {% endfor %}
            </div>
        </div>
</div>


{% endblock %}



{% comment %} <div class="container-fluid">
    
        <div class="row">
            <div>Rste ers eñ te,´ñatre</div>
        </div>
        <div class="row products-main text-center">
            <div class="col-md-4 col-12">
                Producto 1
            </div>
            
            <div class="col-md-4 col-12">
                Producto 2
            </div>
            
            <div class="col-md-4 col-12">
                Producto 3
            </div>
        </div>
    
    </div> {% endcomment %}

pagina/templates/pagina/item_edicion.html
{% extends 'pagina/layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row">
            <div class="col-12 col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-body">
                        <h1>Editar item #{{item.id}}</h1>
                        <form class="" enctype="multipart/form-data" method="post">
                            {% csrf_token %}
                            {{ form | crispy }}
                            <br>
                            <hr>
                            <div class="d-flex justify-content-end">
                                <input type="submit" value="Confirmar Edición" class="btn btn-primary">
                            </div>
                        </form>
                        <div class="justify-content-end">
                            <a type="button" href="{% url 'pagina:index' %}" >Volver al inicio</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

pagina/templates/pagina/item_vista.html
{% extends 'pagina/layout.html' %}
{% block content %}


    <div class="container">
        <div class="w-100">
            <div class="col-12 w-100">
                <div class="card mb-3" >
                    <div class="row g-0">
                        <div class="col-md-6">
                            <img 
                                src="{{media_url}}{{item.imagen.url}}" 
                                class="img-fluid rounded-start" 
                                alt="{{item.titulo}}"
                            >
                        </div>
                        <div class="col-md-6">
                            <div class="card-body">
                                <h4 class="card-title">{{item.titulo}}</h4>
                                <h5 class="card-title"><a style="text-decoration: none; color: black;" href="{% url 'pagina:categoria' item.categoria.id %}" >{{item.categoria}}</a></h5>
                                <hr>
                                <h6 style="text-align:right;">${{item.precio}}</h6>
                                {% if not perms.pagina.change_item and  user.is_authenticated %}
                                <a role="button" class="btn btn-success" href="{% url 'pagina:carrito' item.id %}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-plus" viewBox="0 0 16 16">
                                        <path d="M9 5.5a.5.5 0 0 0-1 0V7H6.5a.5.5 0 0 0 0 1H8v1.5a.5.5 0 0 0 1 0V8h1.5a.5.5 0 0 0 0-1H9V5.5z"></path>
                                        <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zm3.915 10L3.102 4h10.796l-1.313 7h-8.17zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"></path>
                                    </svg>
                                        Agregar al carrito
                                </a>
                                {% endif %}
                                <hr>
                                <p class="card-text">{{item.contenido}}</p>
                                <p class="card-text"><small class="text-muted">Publicado el {{item.fecha_creacion}}</small></p>
                            </div>
                            
                            {% if perms.pagina.change_item %}
                                <div class="col-12 col-md-6 col-sm-12">
                                    <a
                                    style="width: 100%; padding: 0.3em;"
                                    class="btn btn-outline-warning" href="{% url 'pagina:editar' item.id %}">Modificar Item</a>
                                </div>
                            {% endif %}
                            {% if perms.pagina.delete_item %}
                                <div class="col-12 col-md-6 col-sm-12">
                                    <a
                                    style="width: 100%; padding: 0.3em; margin-top: 0.1em;"
                                    class="btn btn-outline-danger btn-block" href="{% url 'pagina:eliminar' item.id %}">Eliminar Item</a>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

pagina/templates/pagina/layout.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Zen+Tokyo+Zoo&display=swap" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <title>Jaguarete KAA webshop</title>
    </head>

    <body style="background-color:light-blue;">
        <header class="">
            <div class=""
                style="
                    background-image: url({% static 'images/logo.jpg' %});
                    min-height: 10em;
                "
            >
                <div class="mt-5 row">
                <div class="col-sm-12 col-md-3 mt-5">
                    <h2 style="padding-left: 0.2em; font-family: 'Zen Tokyo Zoo', cursive; background-color: #000; color: #FFF;" class=>JAGUARETE KAA</h2>
                </div>
                <div class="col-sm-12 col-md-3">
                </div>
                <div id="bloque_login" class="col-12 col-md-6" style="text-align: right; align-items: right;">
                {% comment %} d-grid gap-2 d-md-flex justify-content-md-end {% endcomment %}
                    {% if user.is_authenticated %}
                    <div class="row" style="margin-top: 8em;">
                        <div class="col-sm-12 col-md-4">
                        </div>
                        <div class="col-sm-12 col-md-5">
                            <p style="text-align:center; background-color: rgba(247, 247, 77, 0.59); font-weight: 500; font-size: 1.3em; color: #000;">Estas conectado como: {{ user.get_username }}</p> 
                        </div>
                        <div class="col-md-3 col-sm-12">
                            <a style="margin-right: 0.2em;" role="button" class="btn btn-danger btn-sm" href="{% url 'logout' %}?next={{request.path}}">
                                Salir
                            </a>
                        </div>
                    </div>
                    {% else %}                  
                    <div class="col-sm-12 col-md-6 col-lg-6">
                        <a role="button" class="btn btn-outline-success btn-sm" href="{% url 'login' %}?next={{request.path}}">Acceder</a>
                    </div>
                    {% endif %} 
                </div>
                </div>
            </div>
            
        </header>

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">JGT KAA</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'pagina:index' %}">Home</a>
                    </li>
                   
                    <li class="nav-item dropdown">
                        <div class="dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Categorias
                            </a>
                            <div class="dropdown-menu">
                                {% for categoria in lista_categorias %}
                                    <a class="dropdown-item" href="{% url 'pagina:categoria' categoria.id %}">{{ categoria }}</a>
                                {% endfor %}
                            </div>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pagina:acercade' %}">Acerca de..</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pagina:contacto' %}">Contacto</a>
                    </li>
                    {% if perms.pagina.change_item %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'pagina:nuevo' %}">Nuevo Item</a>
                        </li>
                    {% endif %}

                </ul>
                
                {% if not perms.pagina.change_item and  user.is_authenticated %}
                <div class="btn-group dropdown" style="margin-right: .5em">
                    <a role="button" class="btn btn-light" href="{% url 'pagina:vistaCarrito' %}" >
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-plus" viewBox="0 0 16 16">
                            <path d="M9 5.5a.5.5 0 0 0-1 0V7H6.5a.5.5 0 0 0 0 1H8v1.5a.5.5 0 0 0 1 0V8h1.5a.5.5 0 0 0 0-1H9V5.5z"></path>
                            <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zm3.915 10L3.102 4h10.796l-1.313 7h-8.17zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"></path>
                        </svg> Carrito
                    </a>
                    <button type="button" class="btn btn-outline-light dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                        <span class="visually-hidden">Toggle Dropdown</span>
                    </button>
                    <ul class="dropdown-menu">
                        {% for item in lista_carrito %}                                
                            <li class="list-group-item">{{ item.titulo }}</li>
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}


                <form class="d-flex" method='GET'>
                    <input class="form-control me-2" type="text" placeholder="Busqueda" name="buscar">
                    
                    <button class="btn btn-outline-success" type="submit">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                        </svg> Buscar
                    </button>
                </form>
                </div>
            </div>
        </nav>

        {% comment %} <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> {% endcomment %}


        {% block content %}
        
        {% endblock %}

        <footer class="page-footer font-small">

            <div class="footer-copyright text-center py-3">José Giraudo © 2021 Copyright.
                <p>En nombre de<a href="{% url 'pagina:contacto' %}" class="link-dark"> Juaguarete KAA S.A.</a></p>
            </div>

        </footer>
        

    </body>


</html>